export const FIND_STUDENDCODE_INFO = {
  //학생 생성
  REQUEST: "REQUEST_FIND_STUDENDCODE_INFO",
  SUCCESS: "SUCCESS_FIND_STUDENDCODE_INFO",
  FAILURE: "FAILURE_FIND_STUDENDCODE_INFO",
};

//학생 로그인
export const LOGIN_STUDENT_INFO = {
  REQUEST: "REQUEST_LOGIN_STUDENT_INFO",
  SUCCESS: "SUCCESS_LOGIN_STUDENT_INFO",
  FAILURE: "FAILURE_LOGIN_STUDENT_INFO",
};

//
export const;
