datasource:
  url: jdbc:h2:tcp://localhost/~/querydsl;
  username: sa
  password:
  driver-class-name: org.h2.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org.hibernate.SQL: debug